version: '3.8'
services:
  java-training-api-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: java-training-api-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=java-training-api-db
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume: