spring:
  datasource:
    url: jdbc:h2:mem:java-training-api-db
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enable: true
      path: /h2-console
